FROM ruby:3.2.3

ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev vim postgresql-client

WORKDIR /how_long_will_it_last

COPY . /how_long_will_it_last
